In [1]:
import numpy as np

In [6]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))

In [7]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = (X - m) / std
print(X_norm)

[[ 0.47364408  0.85694657  0.25270676 ..., -0.66287858 -0.04995235
   0.4943421 ]
 [-0.79961521  1.18162604  0.8956213  ...,  0.38484145  1.45360097
  -0.44675035]
 [-1.31587893 -0.17578666 -0.18766408 ..., -2.01306423 -2.04480896
  -0.76758496]
 ..., 
 [ 0.40340088  0.25194632 -0.9890282  ..., -1.52175241 -0.75117684
   1.64236439]
 [-0.41560889  0.87588072  0.04036175 ...,  1.93833629 -0.10909439
   1.0913677 ]
 [-0.05961628 -0.44259085 -1.33900212 ...,  0.19876807  1.12422414
   1.3410552 ]]


In [9]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
Z_sum = np.sum(Z, axis=1)
print(np.nonzero(Z_sum > 10))

(array([1, 4, 5], dtype=int64),)


In [11]:
A = np.eye(3)
B = np.eye(3)
C = np.vstack((A, B))
print(C)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [2]:
import pandas as pd

In [3]:
data = pd.read_csv(r'F:\Reps\ML Voron\titanic.csv', index_col='PassengerId')
data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [15]:
data['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [16]:
data['Survived'].value_counts(normalize=True)

0    0.616162
1    0.383838
Name: Survived, dtype: float64

In [17]:
data['Pclass'].value_counts(normalize=True)

3    0.551066
1    0.242424
2    0.206510
Name: Pclass, dtype: float64

In [18]:
data['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [25]:
# DataFrame.corr(method='pearson', min_periods=1)
data[['SibSp', 'Parch']].corr(method='pearson')

SibSp     Parch
SibSp  1.000000  0.414838
Parch  0.414838  1.000000

In [41]:
names = data.Name
for name in names:
    first_name = name.split('. ')
    first_name = first_name[1].split(' ')
    first_name = first_name[0].strip('()., ')
first_name

Owen
John
Laina
Jacques
William
James
Timothy
Gosta
Oscar
Nicholas
Marguerite
Elizabeth
William
Anders
Hulda
Mary
Eugene
Charles
Julius
Fatima
Joseph
Lawrence
Anna
William
Torborg
Carl
Farred
Charles
Ellen
Lalio
Manuel
William
Mary
Edward
Edgar
Alexander
Hanna
Ernest
Augusta
Jamila
Johan
William
Theodor
Simonne
Margaret
William
Denis
Bridget
Youssef
Josef
Juha
Richard
Henry
Lizzie
Engelhart
Hugh
Emily
Mansouer
Constance
William
Orsen
Amelie
Henry
Harald
Albert
Gerios
Elizabeth
Ernest
Erna
Vincenz
Stephen
Lillian
Ambrose
Apostolos
Lee
Sigurd
Ivan
Rahamin
Alden
Elizabeth
Achille
Jan
Brigdet
Francisco
Bertha
Karl
William
Selman
Mabel
Francesco
Emil
Paul
Herbert
Bertram
Daniel
Charles
George
William
John
Sinai
Matilda
Pastcho
Richard
Gustaf
Anders
Stoytcho
Anna
Albert
Tido
Bertha
Walter
Hileni
David
Katriina
Malake
Edvard
Patrick
William
Quigg
Ellis
Stanley
Leonard
Nicholas
Susan
Percival
Elias
Martin
Fridtjof
Anna
Johan
Jozef
Domingos
Alexander
Leopold
Samuel
Emile
Helen
Jacques
Olaf
Vict

In [43]:
# 577 314 38.38 24.24 29.70 28.00 41.48

In [18]:
df = data[['Pclass', 'Fare', 'Age', 'Sex', 'Survived']]
df = df.dropna(axis=0)
convert_sex = {'female':0, 'male':1}
df['Sex'] = df['Sex'].map(convert_sex)
df_base = df[['Pclass', 'Fare', 'Age', 'Sex']]
df_target = df[['Survived']]
df.head()

Pclass     Fare   Age  Sex  Survived
PassengerId                                      
1                 3   7.2500  22.0    1         0
2                 1  71.2833  38.0    0         1
3                 3   7.9250  26.0    0         1
4                 1  53.1000  35.0    0         1
5                 3   8.0500  35.0    1         0

In [8]:
from sklearn.tree import DecisionTreeClassifier

In [19]:
clf = DecisionTreeClassifier(random_state=241)
clf.fit(df_base, df_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=241,
            splitter='best')

In [20]:
importances = clf.feature_importances_

In [21]:
print(importances)

[ 0.14000522  0.30343647  0.2560461   0.30051221]
